language: java
sudo: required
dist: trusty

env:
  global:
    - MODULE_ID=cbmongodb
  matrix:
    - ENGINE=lucee@4.5
    - ENGINE=lucee@5

before_install:
   # CommandBox Keys
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
    /etc/apt/sources.list.d/commandbox.list
   # MongoDB Manual Install - Travis' is still at 2.6
  - sudo apt-get update && sudo apt-get --assume-yes install mongodb-org zip unzip commandbox
  - mongo --version
  - mkdir $TRAVIS_BUILD_DIR/mongodb
  - mongod --fork  --dbpath $TRAVIS_BUILD_DIR/mongodb/ --logpath $TRAVIS_BUILD_DIR/mongodb.log
 

install:
  # Install Commandbox
  - sudo apt-get update && sudo apt-get --assume-yes install rsync jq commandbox
  # Test that the box binary is available and ready for our tests
  - box version
  # If using auto-publish, you will need to provide your API token with this line:
  - box config set endpoints.forgebox.APIToken=$FORGEBOX_API_TOKEN > /dev/null
  # Setup for our tests
  - mkdir tests/results
  - sudo chmod -R 775 tests/results

# Build script - note module versioning is passed to ANT
script:
  # run our dependency install to ensure the workbench is in place
  - box install
  # add our module-specific build properties
  - printf "\nmodule.name=$MODULE_ID" >> workbench/build.properties
  - printf "\ncfengine=$ENGINE" >> workbench/build.properties
  - printf "\nbuild.branch=$TRAVIS_BRANCH" >> workbench/build.properties
  # execute our build
  - sudo ant -DisTravis=true -Dbuild.number=$TRAVIS_BUILD_NUMBER -f workbench/build.xml

after_failure:
  - cd $TRAVIS_BUILD_DIR
  # Display the contents of our root directory
  # Spit out our Commandbox log in case we need to debug
  - box server log name=$ENGINE
  - cat `box system-log`

# Only executed when merging to master 
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p s3deploy
  - rsync -av ./artifacts/$MODULE_ID/ ./s3deploy/
  - rm -f ./s3deploy/box-repo.json

deploy:
  on:
    branch: 
      - master
      - development
    condition: "$ENGINE = lucee@4.5"
  skip_cleanup: true
  provider: s3
  #AWS Credentials need to be set in Travis
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET
  bucket: "oss.silowebworks.com"
  local-dir: s3deploy
  upload-dir: coldbox-modules/cbmongodb
  acl: public_read

after_deploy:
  - cd $TRAVIS_BUILD_DIR/build && box forgebox publish
