language: java
sudo: required
dist: trusty

env:
  global:
    - RELEASE_VERSION="3.2.1.1"
    - RELEASE_PLACEHOLDER="@release.number@"
    - BUILD_PLACEHOLDER="@build.number@"

before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - sudo echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee -a /etc/apt/sources.list.d/mongodb-org-3.2.list

install:
  # MongoDB Manual Install - Travis' is still at 2.6
  - sudo apt-get update && sudo apt-get --assume-yes install mongodb-org zip unzip commandbox
  - mongo --version
  - sudo mongod --fork --logpath $TRAVIS_BUILD_DIR/mongodb.log
  # Test that the box binary is available and ready for our tests
  - box version

script:
  - sudo ant -DisTravis=true -f workbench/build.xml

before_deploy:
  - mkdir s3deploy
  - cp -r ./artifacts/cbmongodb/* ./s3deploy/
  - rm -f ./s3deploy/box-repo.json

deploy:
  on:
    branch: 
      - master
  skip_cleanup: true
  provider: s3
  #AWS Credentials need to be set in Travis
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET
  bucket: "oss.silowebworks.com"
  local-dir: s3deploy
  upload-dir: oldbox-modules/cbmongodb
  acl: public_read

after_deploy:
  - cd $TRAVIS_BUILD_DIR/build && box forgebox login username=$FORGEBOX_USERNAME password=$FORGEBOX_PASSWORD && box forgebox publish
